config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/success', to: "pages#success"

  get 'coaches', to: 'users#index'

  get 'all_orders', to: "orders#index"

  get '/:username', to: "users#show"
  get '/:username/:date', to: "users#slots_date"

  resources :slots, only: [:show, :index] do
    resources :orders, only: [:new, :create, :show]
    resources :reviews, only: [:new, :create]
    get 'confirmed', to: 'orders#confirmed'
  end

  # get 'orders/:order_id/reviews/new', to: 'reviews#new', as: :review_new
  # post 'orders/:order_id/reviews', to: 'reviews#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coach_game.rb
class CoachGame < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :coach_games, dependent: :destroy
  has_many :users, through: :coach_games

  validates :name, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :slot
  belongs_to :user
  has_one :review, dependent: :destroy

  monetize :paid_amount_cents
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :order
  belongs_to :user
end

app/models/slot.rb
class Slot < ApplicationRecord
  belongs_to :user
  has_one :order, dependent: :destroy

  scope :available, -> { where(booked: false) }
  scope :by_user, ->(user) { where('user_id = ?', user) }
  scope :by_date, ->(date) { where('date = ?', date) }

  def duration
    (self.end - self.start)/(60*60)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :coach_games, dependent: :destroy
  has_many :games, through: :coach_games
  has_many :slots
  has_many :orders
  has_many :booked_slots, through: :orders, source: :slot
  has_many :reviews, dependent: :destroy

  validates :email, presence: true, uniqueness: true, format: { with: /\w+(\.\w+)?@\w+.\w{2,3}/ }
  validates :password, presence: true
  validates :username, uniqueness: true
  validates :rates, numericality: true, allow_nil: true

  scope :filter_username, -> given_username { where("username ILIKE ?", given_username) }
  scope :filter_country, -> given_country { where("country ILIKE ?", given_country) }
  scope :filter_price, -> min_price, max_price { where("rates >= ? AND rates <= ?", min_price, max_price) }
  scope :filter_game, -> (given_game) { joins(:games).where(games: {name: given_game}) }
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def new
    @order = Order.new
    @order.slot = Slot.find(params[:slot_id].to_i)
    @slot = @order.slot
    @order.paid_amount = @slot.duration * @slot.user.rates
  end

  def create
    @slot = Slot.find(params[:slot_id])
    @order = Order.new
    @order.slot = @slot
    @order.user = current_user
    @order.paid_amount = @slot.user.rates * @slot.duration
    @order.status = "pending"

    if @order.save!
      @order.slot.booked = true
      @order.slot.save
      @session = Stripe::Checkout::Session.create({
        line_items: [{
          # Provide the exact Price ID (e.g. pr_1234) of the product you want to sell
          price_data: {
            currency: 'usd',
            product_data: {
              name: "session with #{@slot.user.username}"
            },
            unit_amount: @slot.user.rates * @slot.duration.to_i * 100
          },
          quantity: 1
        }],
        mode: 'payment',
        success_url: "#{root_url}success.html",
        cancel_url: "#{root_url}cancel.html"
      })
      redirect_to @session.url
      else
        render :new
      end
  end

  def show
    @order = Order.find(params[:id])
  end

  def index
    @orders = current_user.orders
  end

  def confirmed
    @slot = Slot.find(params[:slot_id])
    @order = @slot.order
    @order.status = "confirmed"
    @order.save!
  end

  private

  def order_params
    params.require(:order).permit(:slot_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @games = Game.all
  end



end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @current_user = current_user
    @slot = Slot.find(params[:slot_id])
    if @current_user = @slot.order.user
      @review = Review.new
    end
  end

  def create
    @current_user = current_user
    @slot = Slot.find(params[:slot_id])
    if @current_user = @slot.order.user
      @review = Review.new(reviews_params)
      @review.user = @slot.user
      @review.order = @slot.order
      if @review.save!
        redirect_to "/#{@slot.user.username}"
      else
        render :new
      end
    end
  end

  private

  def reviews_params
    params.require(:review).permit(:content, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  has_scope :filter_country
  has_scope :filter_username
  has_scope :filter_price, using: %i[min_price max_price], type: :hash
  has_scope :filter_game

  def index
    @users = apply_scopes(User).all
  end

  def show
    @user = User.find_by(username: params[:username])


    @coach_slots = Slot.by_user(@user)
    @available_slots = @coach_slots.available
    @available_dates = @available_slots.map { |slot| slot.date }
    @reviews_count = @user.reviews.count.to_f

    unless @reviews_count.zero?
      @avg_rating = @user.reviews.average("rating").to_i
      @reviews = @user.reviews
    end
    @booked_dates = get_booked_dates(current_user) if user_signed_in?
  end

  def get_booked_dates(user)
    # get all the coach's slots booked by the user
    slots_booked_by_current_user = current_user.booked_slots do |slot|
      slot if slot.user == @user
    end

    slots_booked_by_current_user.map { |slot| slot.date }


  end

  def slots_date
    @user = User.find_by(username: params[:username])
    @date = Date.parse(params[:date])
    @availables = @user.slots.select { |slot| (slot.date == @date) && (slot.booked == false)}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table
  end

  class Calendar < Struct.new(:view, :date, :callback)
    HEADER = %w[Sunday Monday Tuesday Wednesday Thursday Friday Saturday]
    START_DAY = :sunday

    delegate :content_tag, to: :view

    def table
      content_tag :table, class: "calendar" do
        header + week_rows
      end
    end

    def header
      content_tag :tr do
        HEADER.map { |day| content_tag :th, day }.join.html_safe
      end
    end

    def week_rows
      weeks.map do |week|
        content_tag :tr do
          week.map { |day| day_cell(day) }.join.html_safe
        end
      end.join.html_safe
    end

    def day_cell(day)
      content_tag :td, view.capture(day, &callback), class: day_classes(day)
    end

    def day_classes(day)
      classes = []
      classes << "today" if day == Date.today
      classes << "notmonth" if day.month != date.month
      classes.empty? ? nil : classes.join(" ")
    end

    def weeks
      first = date.beginning_of_month.beginning_of_week(START_DAY)
      last = date.end_of_month.end_of_week(START_DAY)
      (first..last).to_a.in_groups_of(7)
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Best Gamer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/orders/_new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Make a booking with a coach</h3>
        <%= simple_form_for @order do |f| %>
          <%= f.input :duration, collection: 1..10 %>
          <%= f.submit class: 'btn btn-flat' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/orders/_order.html.erb
<div class="card w-100 bg-secondary my-2">
  <div class="card-body">
    <h5 class="card-title">Order id #<%= order.id %>: Session with <%= order.slot.user.username %></h5>
    <p class="card-text text-left"><%= order.slot.duration %> hours on <strong><%= order.slot.date.strftime("on %d %b %Y, %A") %></strong></p>
    <span class='badge badge-pill badge-light mx-2'><%=order.status%></span>
    <% if order.status == "confirmed"%>
    <a href="/slots/<%=order.slot_id%>/reviews/new" class="btn btn-outline-light">Review your coach</a>
    <%end%>
    <% if order.status == "pending"%>
    <a href="<%=slot_order_path(order.slot, order)%>" class="btn btn-outline-light">Complete your order</a>
    <%end%>
  </div>

</div>

app/views/orders/confirmed.html.erb
<div class="container mt-3 mx-auto text-center">
  <h1>congrats!</h1>
  <h3>your order has been confirmed</h3>
  <a class="btn btn-primary" href=<%="/#{@order.slot.user.username}"%>>book more slots</a>
</div>

app/views/orders/index.html.erb
<h1>All your orders</h1>
<div class="container">
  <%= render @orders %>
</div>

app/views/orders/new.html.erb
<h1 class="text-center">Checkout</h1>
<div class="container mx-auto">
  <div class="row">
    <div class="col-sm-6">
      <div class="card border p-3 h-100 my-1">
        <p class="font-weight-bolder">Your Order</p>
        <div class="d-flex align-items-center">
          <img src=<%=@order.slot.user.profile_picture%> alt="", style="width:200px;">
          <%= @slot.start.strftime("%l:%M %p") %> to <%= @slot.end.strftime("%l:%M %p") %> with <%= @order.slot.user.username %>
        </div>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="card border p-3 h-100">
        <p class="font-weight-bolder">Your Details</p>
            <div class="form-group">
              <label for="exampleFormControlSelect1">Currency</label>
              <select class="form-control" id="exampleFormControlSelect1">
                <option>USD</option>
                <option>SGD</option>
                <option>RMB</option>
                <option>AUD</option>
                <option>CAD</option>
              </select>
            </div>
            <div class="d-flex justify-content-between">
              <div class="amount">
                <p class="mt-5 font-weight-bolder">Your Total</p>
                <h3><%= humanized_money_with_symbol(@order.paid_amount) %></h3>
              </div>
            </div>
          <%=simple_form_for([@slot,@order]) do |f|%>
            <%=f.button :submit, class: "btn btn-primary" %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/orders/show.html.erb
<h1 class="text-center">Confirm your order</h1>
<div class="container">
  <div class="container m-2 border p-3">
    <p>YOUR ORDER</p>
    <div class="container">
      <img src=<%=@order.slot.user.profile_picture%> alt="", style="width:200px;">


      <%= pluralize @order.slot.duration, "hour" %> with <%= @order.slot.user.username %>
    </div>
  </div>
  <div class="container m-2 border p-3">
      <div class="d-flex justify-content-between">
        <div class="amount">
          <p>YOUR TOTAL</p>
          <h3><%= humanized_money_with_symbol(@order.paid_amount) %></h3>
        </div>
        <input type="hidden" value=<%=@order%>>
        <a href="<%=slot_confirmed_path(@order.slot)%>"  class="btn btn-primary my-auto rounded-pill"> Confirm Your Order </a>
      </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class='container-fluid padding-zero'>
  <div class='home-background-image'>
  <div class='home-text text-center pb-5 mb-5'>
    <h2 class="text-center">I want to <strong>go pro</strong> in</h2>
    <form action="/coaches">
      <div class="form-custom">
        <div>
          <select name="filter_game", class="form-content">
            <% @games.all.each do |game| %>
              <option value="<%= game.name %>", class="dropdown-content"><%= game.name %></option>
            <% end %>
          </select>
        </div>
        <input type="submit", class="btn-primary submit-btn", value="Find your coach">
      </div>
    </form>
  </div>
  </div>
</div>

<div class='container row align-items-center'>
  <div class='home-cards col-sm-4'>
    <div class='card-home'>
      <i class="fas fa-gamepad"></i>
      <div class='card-home-body'>
        <h3>Pick Your Game</h3>
        <p>We provide coaching lessons for the most popular online games by the best coaches available.</p>
      </div>
    </div>

    <div class='card-home'>
      <i class="fas fa-chalkboard-teacher"></i>
      <div class='card-home-body'>
        <h3>Find your coach</h3>
        <p>With the help of our carefully engineered algorithm, we make it easy for you to find your perfect coach.</p>
      </div>
    </div>
  </div>

  <div class='img-arrow col-sm-4'>
    <i class="fas fa-angle-double-right"></i>
  </div>

  <div class='card-home col-sm-4'>
    <i class="fas fa-trophy"></i>
    <div class='card-home-body'>
      <h3>Become A Pro</h3>
      <p>Start your lessons with our coach to begin reaching your in-game goals and become a professional player.</p>
    </div>
  </div>
</div>

app/views/pages/success.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thanks for your order!</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <section class="text-center">
    <p class="text-center">
      We appreciate your business! If you have any questions, please email
      <a href="mailto:orders@example.com">orders@example.com</a>.
    </p>
    <%= link_to  "back to home", root_url, class: "btn btn-primary text-center" %>
  </section>
</body>
</html>

app/views/reviews/new.html.erb
<div class="container">
  <h1>Review <%= @slot.user.username %></h1>
  <p>Session date: <%= @slot.date %></p>

  <%= simple_form_for [@slot, @review] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating, collection: 1..5 %>
    <%= f.button :submit, "Submit", class: 'btn btn-primary' %>

  <% end %>
</div>

app/views/shared/_avatar.html.erb
<%= image_tag(@user.profile_picture, class: "avatar-large") %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<% @games = Game.all %>


<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand custom-nav-item" do %>
    <%= image_tag "logo.jpg", class:"img-size" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle custom-nav-item" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
            Game
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% @games.all.each do |game| %>
              <a class="dropdown-item" href="/coaches/?filter_game=<%= game.name %>"><%= game.name %></a>
            <% end %>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle custom-nav-item" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
            Members Area
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">My Profile</a>
            <a class="dropdown-item" href="/all_orders">Orders</a>
            <a class="dropdown-item" href="<%=destroy_user_session_path%>", data-method="delete">Logout</a>
          </div>
        </li>
      <% else %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle custom-nav-item" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
            Game
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% @games.all.each do |game| %>
              <a class="dropdown-item" href="/coaches/?filter_game=<%= game.name %>"><%= game.name %></a>
            <% end %>
          </div>
        </li>
        <li class="nav-item ">
          <%= link_to "Login", new_user_session_path, class: "nav-link custom-nav-item btn btn-outline-warning" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('<simple_calendar.previous>', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading mb-2">
    <%= link_to t('simple_calendar.previous', default: '<'), calendar.url_for_previous_view, class: "btn-primary px-2" %>
    <span class="calendar-title font-weight-bolder"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: '>'), calendar.url_for_next_view, class: "btn-primary px-2" %>
  </div>

  <table class="table table-striped">
    <thead class="table-headers">
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/slots/_index.html.erb
<%= user.slots %>
<% raise %>

app/views/users/_form.html.erb
<form>
  <div class="form-group">
    <label for="minimum">Min</label>
    <input type="price" class="form-control" id="minprice" aria-describedby="minprice">
  </div>
  <div class="form-group">
    <label for="maximum">Max</label>
    <input type="price" class="form-control" id="maxprice" aria-describedby="maxprice">
  </div>
</form>

app/views/users/_user.html.erb
<div class="col-sm-4">
  <div class="my-3">
    <div class="card h-100 mb-3">

    <%= link_to "/#{user.username.gsub(" ","")}" do %>

      <%= image_tag(user.profile_picture, class:"d-block mx-auto") %>

      <div class="card-body custom-text">
        <h3 class="card-title text-center"><%= user.username %></h3>
        <p class="card-text font-weight-bold">$<%= user.rates %>/hr</p>
        <p class="card-text ">Orders Completed: <%= user.slots.where("booked = true").count %></p>
      </div>

      <div class='ratings-stars text-center mb-2'>
        <% if (user.reviews.length) > 0 %>
          <% (((user.reviews.map(&:rating).reduce(:+)).to_i)/(user.reviews.length)).times do %>
            <i class="fas fa-star star-yellow"></i>
          <% end %>
        <% else %>
          <p class="text-center text-light">Be the first to review!</p>
        <% end %>
      </div>

      <div class="btn-margin">
        <a class="btn btn-primary border-rounded" href=<%="/#{user.username.gsub(" ","")}"%>>Find out more</a>
      </div>
    <% end %>
  </div>
  </div>
</div>

app/views/users/filter_by_game.html.erb
<div>
  <h1>Our Coaches</h1>
  <p>Become the better gamer in League of Legends. Get coaching to reach Challenger!</p>
</div>

<%= form_with url: "/coaches/:id", method: :get do |f| %>
  <%= f.label :username, "Search for coach by name:" %>
  <%= f.text_field :username %>
  <%= f.label :country %>
  <%= f.text_field :country %>
  <label for="customRange3" class="form-label">Price</label>
  <input type="range" class="form-range" min="10" max="100" step="1" id="customRange3">
  <%= f.submit "Search" %>
<% end %>

<%= render @users %>

app/views/users/index.html.erb
<div class="wrapper p-5">
  <div>
    <h1 class='text-center'>Our Coaches</h1>
    <h2 class='text-center'>Become the BEST gamer in <%= params[:filter_game] %>. Get coaching to reach the next level!</h2>
  </div>
  <nav class="navbar navbar-dark navbar-expand-lg">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <div class="mt-5 mx-auto py-4 px-5 form-wrapper">
        <form action="#" method="get" class="text-center">
          <input name="filter_game" type="hidden" value="<%= params[:filter_game] %>" />
          <div class="row">
            <div class="col-sm-3">
              <div class="text-left h-100 d-flex flex-column justify-content-between">
                <label for="filter_username" class="text-uppercase font-weight-bolder">search coach by name</label>
                <input type="text" class="form-control" name="filter_username" placeholder="e.g. Milo" value="<%= params[:filter_username]%>">
              </div>
            </div>
            <div class="col-sm-3">
              <div class="text-left h-100 d-flex flex-column justify-content-between">
                <label for="filter_country" class="text-uppercase font-weight-bolder">Country</label>
                <input type="text" class="form-control" name="filter_country" placeholder="e.g. Singapore" value="<%= params[:filter_country]%>">
              </div>
            </div>
            <div class="col-sm-3">
              <div class="text-left h-100 d-flex flex-column justify-content-between" >
                <label for="filter_price[min_price]" class="text-uppercase font-weight-bolder">Min price</label>
                <input type="number" class="form-control" name="filter_price[min_price]" placeholder="0" value="<%= params[:filter_price["min_price"]]%>">
              </div>
            </div>
            <div class="col-sm-3">
              <div class="text-left h-100 d-flex flex-column justify-content-between">
                <label for="filter_price[max_price]" class="text-uppercase font-weight-bolder">Max price</label>
                <input type="number" class="form-control" name="filter_price[max_price]" placeholder="100" value="<%= params[:filter_price["max_price"]]%>">
              </div>
            </div>
          </div>
          <div class='text-center mt-3'>
            <input type="submit" value="Find your coach!" class="btn btn-primary btn-lg">
          </div>
        </form>
      </div>
    </div>
  </nav>

</div>

  <div class="mt-4 mx-5">
    <div class="row">
      <%= render @users %>
    </div>
  </div>
</div>

app/views/users/slots_date.html.erb
<h1>Slots for <%=@user.username%></h1>
<h3 class="text-center mb-5"><%=@date.strftime("on %d %b %Y, %A")%></h3>

<div class="container">
  <%if @availables.empty?%>
    <h4>Nothing here</h4>
  <% else %>
    <% @availables.each do |slot| %>
      <div class="card bg-secondary px-3">
        <div class="d-flex justify-content-between align-items-center">
          <div>
            <h5 class="card-title mt-2"><%= slot.start.strftime("%l:%M %p") %> to <%= slot.end.strftime("%l:%M %p") %></h5>
          </div>
          <div>
            <a href=<%=new_slot_order_path(slot)%> class="btn btn-primary">Book now</a>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>
<div class='container d-flex align-items-center justify-content-center mt-4'>
  <%= link_to "Back to User", "/#{params[:username]}", :class=>'btn btn-primary' %>
</div>